services:
  frontend:
    build:
      context: ./frontend
      args:
        NEXT_PUBLIC_IMAGE_BASE_URL: ${NEXT_PUBLIC_IMAGE_BASE_URL}
    container_name: scshin-dev-frontend
    environment:
      API_URL: ${API_URL}
      NEXT_PUBLIC_IMAGE_BASE_URL: ${NEXT_PUBLIC_IMAGE_BASE_URL}
      NODE_ENV: production
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    container_name: scshin-dev-backend
    build:
      context: ./backend
    environment:
      TZ: "Asia/Seoul"
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./volumes/uploads:/home/uploads
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: scshin-dev-database
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./volumes/data:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test -d test"]
      interval: 5s
      timeout: 3s
      retries: 20