
create sequence if not exists role_seq start with 1 increment by 50;

create sequence if not exists users_seq start with 1 increment by 50;

create table if not exists category (
                          is_visible boolean default true,
                          sort_order integer default 0,
                          created_at timestamp(6),
                          id bigint generated by default as identity,
                          parent_id bigint,
                          updated_at timestamp(6),
                          theme_color varchar(32),
                          icon varchar(64),
                          slug varchar(128) not null unique,
                          description varchar(255),
                          name varchar(255) not null,
                          primary key (id)
);

create table if not exists post (
                      author_id bigint not null,
                      created_at timestamp(6),
                      id bigint generated by default as identity,
                      updated_at timestamp(6),
                      content TEXT,
                      title varchar(255) not null,
                      primary key (id)
);

create table if not exists role (
                      id bigint not null,
                      user_id bigint,
                      name varchar(255) unique,
                      primary key (id)
);

create table if not exists users (
                       id bigint not null,
                       email varchar(255) unique,
                       name varchar(255),
                       password varchar(255),
                       primary key (id)
);

alter table if exists category
    add constraint FK2y94svpmqttx80mshyny85wqr
    foreign key (parent_id)
    references category;

alter table if exists role
    add constraint FKgg3583634e0ydkacyk8wbbm19
    foreign key (user_id)
    references users;