DROP TABLE IF EXISTS category CASCADE;

CREATE TABLE category (
    id BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
    parent_category_id BIGINT NULL,
    category_name      VARCHAR(128) NOT NULL,
    slug               VARCHAR(128) NOT NULL,
    description        TEXT NULL,

    sort_order         INTEGER NOT NULL DEFAULT 0,
    depth              INTEGER NOT NULL DEFAULT 1,

    use_yn             CHAR(1) NOT NULL DEFAULT 'Y',
    created_at         TIMESTAMP(6) NOT NULL DEFAULT NOW(),
    updated_at         TIMESTAMP(6) NULL,

    CONSTRAINT fk_category_parent
      FOREIGN KEY (parent_category_id)
          REFERENCES category(id)
          ON DELETE SET NULL,

    CONSTRAINT uq_category_slug UNIQUE (slug),
    CONSTRAINT chk_category_use_yn CHECK (use_yn IN ('Y', 'N'))
);

CREATE TABLE category_post (
    category_id BIGINT NOT NULL,
    post_id BIGINT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL DEFAULT NOW(),

    PRIMARY KEY (category_id, post_id),

    CONSTRAINT fk_category_post_category FOREIGN KEY (category_id) REFERENCES category(id) ON DELETE CASCADE,
    CONSTRAINT fk_category_post_post FOREIGN KEY (post_id) REFERENCES post(id) ON DELETE CASCADE
)